//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SayoDeviceStreamingAssistant.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SayoDeviceStreamingAssistant.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackButton_ToolTip {
            get {
                return ResourceManager.GetString("BackButton.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config sources.
        /// </summary>
        public static string ConfigSourcesButton_ToolTip {
            get {
                return ResourceManager.GetString("ConfigSourcesButton.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device does not support streaming.
        /// </summary>
        public static string DeviceInfo_UpdateStatus_Device_does_not_support_streaming {
            get {
                return ResourceManager.GetString("DeviceInfo_UpdateStatus_Device_does_not_support_streaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is disconnected.
        /// </summary>
        public static string DeviceInfo_UpdateStatus_Device_is_disconnected {
            get {
                return ResourceManager.GetString("DeviceInfo_UpdateStatus_Device_is_disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string DeviceInfo_UpdateStatus_Disconnected {
            get {
                return ResourceManager.GetString("DeviceInfo_UpdateStatus_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Supported.
        /// </summary>
        public static string DeviceInfo_UpdateStatus_Not_Supported {
            get {
                return ResourceManager.GetString("DeviceInfo_UpdateStatus_Not_Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused: {0}.
        /// </summary>
        public static string DeviceInfo_UpdateStatus_Paused___0_ {
            get {
                return ResourceManager.GetString("DeviceInfo_UpdateStatus_Paused___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string DeviceInfo_UpdateStatus_Ready {
            get {
                return ResourceManager.GetString("DeviceInfo_UpdateStatus_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming: {0}.
        /// </summary>
        public static string DeviceInfo_UpdateStatus_Streaming___0_ {
            get {
                return ResourceManager.GetString("DeviceInfo_UpdateStatus_Streaming___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available devices..
        /// </summary>
        public static string label_Content {
            get {
                return ResourceManager.GetString("label.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string labelName_Content {
            get {
                return ResourceManager.GetString("labelName.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string labelType_Content {
            get {
                return ResourceManager.GetString("labelType.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset transform.
        /// </summary>
        public static string ResetPreviewRect_ToolTip {
            get {
                return ResourceManager.GetString("ResetPreviewRect.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select content type.
        /// </summary>
        public static string SourceCombo_ToolTip {
            get {
                return ResourceManager.GetString("SourceCombo_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source {0}.
        /// </summary>
        public static string SourcesManagePage_AddNewButton_Click_Source__0_ {
            get {
                return ResourceManager.GetString("SourcesManagePage_AddNewButton_Click_Source__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select video file.
        /// </summary>
        public static string SourcesManagePage_SelectFileButton_Click_Select_video_file {
            get {
                return ResourceManager.GetString("SourcesManagePage_SelectFileButton_Click_Select_video_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        public static string SourcesManagePage_SetContentUiByType_Monitor {
            get {
                return ResourceManager.GetString("SourcesManagePage_SetContentUiByType_Monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video path.
        /// </summary>
        public static string SourcesManagePage_SetContentUiByType_Video_path {
            get {
                return ResourceManager.GetString("SourcesManagePage_SetContentUiByType_Video_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string SourcesManagePage_SetContentUiByType_Window {
            get {
                return ResourceManager.GetString("SourcesManagePage_SetContentUiByType_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string SourcesManagePage_SourceTypes_Media {
            get {
                return ResourceManager.GetString("SourcesManagePage_SourceTypes_Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin streaming.
        /// </summary>
        public static string StreamButton_ToolTip {
            get {
                return ResourceManager.GetString("StreamButton.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin streaming.
        /// </summary>
        public static string StreamingPage_SetStreamButton_Begin_streaming {
            get {
                return ResourceManager.GetString("StreamingPage_SetStreamButton_Begin_streaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause streaming.
        /// </summary>
        public static string StreamingPage_SetStreamButton_Pause_streaming {
            get {
                return ResourceManager.GetString("StreamingPage_SetStreamButton_Pause_streaming", resourceCulture);
            }
        }
    }
}
